### ISSUE TITLE
Trouble finding some lyrics

### ISSUE THREAD

**Issue by mictyan** [alireza6677/lyrics-finder-gnome-ext#10]
Hello, my main question is where does it search for the lyrics?
I've having some trouble to find for some Brazilian songs. In the begin I thought it was because I was hearing some new or no so popular music, but I did some tests and it fails to find some more popular ones too. And all this songs lyrics are readly available on genius or some other sites.
I'm using spotify to listem to them.

Thanks! other than this, I love your extension!

**Comment by TheWeirdDev** [comment]
Hi, Thanks for reporting the issue.
I'm using a free Chinese API to fetch the lyrics and it doesn't have a complete database of all songs. There are paid APIs but i can't afford them and also they are unavailable in my country (Iran) due to the sanctions.
I currently have no plan to rewrite the extension unless i find a better free API.

**Comment by mictyan** [comment]
I see!
if I can help with anything about this, just send a message!

And you did not said the name of the API, one way I can help (not the best, but works) is to add new lyrics to their database.

**Comment by TheWeirdDev** [comment]
The API is visible in the [source code](https://github.com/TheWeirdDev/lyrics-finder-gnome-ext/blob/b06cafad211d93ec4245bfffb78222ab1ab88561/lyrics_api.js#L21), it's from http://music.163.com

I don't know if you can submit new lyrics to their database. If you found a way, that would be awesome.
